services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: expense-tracker-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ExpenseTracker123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - expense-tracker-network

  # Backend API
  backend:
    build:
      context: ./backend/ExpenseTracker.Api
      dockerfile: Dockerfile
    container_name: expense-tracker-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ExpenseTrackerDb;User Id=sa;Password=ExpenseTracker123!;TrustServerCertificate=true;
    ports:
      - "5050:8080"
    depends_on:
      - sqlserver
    networks:
      - expense-tracker-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense-tracker-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - expense-tracker-network

volumes:
  sqlserver_data:

networks:
  expense-tracker-network:
    driver: bridge